name: Ratios

on:
  workflow_dispatch:
  schedule:
    - cron: "*/15 * * * *"

jobs:
  run:
    runs-on: ubuntu-latest

    env:
      TELEGRAM_BOT: ${{ secrets.TELEGRAM_BOT }}
      TELEGRAM_CHAT: ${{ secrets.TELEGRAM_CHAT }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Restore previous state
        uses: actions/download-artifact@v4
        with:
          name: state
        continue-on-error: true

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install axios
        run: npm install axios

      - name: Run script
        run: node script.js

      - name: Save state
        uses: actions/upload-artifact@v4
        with:
          name: state
          path: state.json
        if: always()
